export { Header } from "./Header";
export { Button } from "./Button";
export { Img } from "./Img";
export { List } from "./List";
export { Text } from "./Text";
export { LetterLast } from "./Text";
export { HighText } from "./HighText";
export { TextBlock } from "./TextBlock"
export { InstructBlock } from "./InstructBlock"
export { Instruction } from "./Instruction"
export { Building } from "./Building"
export { ListBuilding } from "./ListBuilding"
export { Audience } from "./Audience"
export { ListAudience } from "./ListAudience"
export { LoginForm } from "./LoginForm"
export { Modal} from "./Modal"
export { ModalReservation } from "./ModalReservation"
export { ProtectedRoute } from "./ProtectedRoute"
export { LoadingImg } from "./LoadingImg"
